# This workflow runs update-readme.py which updates README.md file.

name: Update readme # GitHub Actions 탭에서 확인할 수 있는 액션 이름

on: # jobs가 실행되어야 하는 상황 정의
  push:
    branches: [main] # main 브랜치에 push가 발생했을 때
  pull_request:
    branches: [main] # main 브랜치에 pull request가 발생했을 때

jobs: # 실제 실행될 내용
  build:
    runs-on: ubuntu-latest # 빌드 환경
    steps:
      - uses: actions/checkout@v3 # checkout
      - name: Set up Python 3.10
        uses: actions/setup-python@v3 # setup-python
        with:
          python-version: "3.10" # 3.10버전 파이썬 사용
      - name: Run update_readme_script # 2) update-readme.py 실행
        working-directory: scripts
        run: |
          python update_readme_script.py
      - name: Commit changes # 3) 추가된 파일 commit
        run: |
          git config --global user.name 'KimWooHyun' # 유저명
          git config --global user.email 'ktkwhms3@gmail.com' # 유저 이메일
          git add -A
          git commit -am "auto-update README.md" # 커밋 메시지
      - name: Push changes # 4) master에 푸시
        run: |
          git push
